services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php_base:
        build: .docker/php
        container_name: php_base
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
            - 5173:5173
        volumes:
            - .:/var/www:cached
        networks:
            - laravel_base

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx_base:
        image: nginx
        container_name: nginx_base
        restart: unless-stopped
        tty: true
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php_base
            - mysql_base
        networks:
            - laravel_base
    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    mysql_base:
        image: mysql/mysql-server:8.0
        container_name: mysql_db_base
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
        networks:
            - laravel_base

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin_base:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_db_base
        restart: unless-stopped
        tty: true
        ports:
            - 8080:80
        links:
            - mysql_base
        environment:
            PMA_HOST: mysql_base
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
        networks:
            - laravel_base

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail_base:
        image: axllent/mailpit:latest
        container_name: mail_base
        restart: unless-stopped
        tty: true
        ports:
            - 8025:8025
            - 1025:1025
        networks:
            - laravel_base

networks:
    laravel_base:
        driver: bridge